name = "moe-counter-cf"
account_id = "52cfXXXXXXXXXXXXXXXXXXXXXX"
workers_dev = true
compatibility_date = "2024-11-19"

kv_namespaces = [
  { binding = "KV", id = "6323bbaXXXXXXXXXXXXXXXXXX" },
]

[build]
command = "npm run build"

main = "./dist/worker.js"

